/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Marseal
 */
public class BiodataOrganisasi14 extends javax.swing.JFrame {
    private Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
    /**
     * Creates new form BiodataOrganisasi14
     */
    public BiodataOrganisasi14() {
        initComponents();
        setLocation(dimensi.width / 2 - getWidth() / 2, dimensi.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jkBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTA = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lakiRB = new javax.swing.JRadioButton();
        prRB = new javax.swing.JRadioButton();
        ctk = new javax.swing.JLabel();
        tebalCB = new javax.swing.JCheckBox();
        miringCB = new javax.swing.JCheckBox();
        mrg = new javax.swing.JLabel();
        tampilBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        tutupBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        hasilTA = new javax.swing.JTextArea();
        pekerjaanCB = new javax.swing.JComboBox<>();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Pekerjaan");

        jLabel3.setText("Alamat");

        alamatTA.setColumns(20);
        alamatTA.setRows(5);
        jScrollPane1.setViewportView(alamatTA);

        jLabel4.setText("Jenis Kelamin");

        jkBtnGroup.add(lakiRB);
        lakiRB.setText("Laki-laki");
        lakiRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRBActionPerformed(evt);
            }
        });

        jkBtnGroup.add(prRB);
        prRB.setText("Perempuan");

        ctk.setText("Cetak tebal");

        tebalCB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tebalCBStateChanged(evt);
            }
        });

        miringCB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                miringCBStateChanged(evt);
            }
        });

        mrg.setText("Cetak miring");

        tampilBtn.setText("Tampil");
        tampilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        tutupBtn.setText("Tutup");
        tutupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupBtnActionPerformed(evt);
            }
        });

        hasilTA.setColumns(20);
        hasilTA.setRows(5);
        jScrollPane3.setViewportView(hasilTA);

        pekerjaanCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karyawan Swasta", "Pengusaha", "Pegawai Negeri Sipil", "Wiraswasta", "Ibu Rumah Tangga", "Lainnya" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(namaTF)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tampilBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(clearBtn)
                        .addGap(80, 80, 80)
                        .addComponent(tutupBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lakiRB)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ctk)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tebalCB)))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prRB)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mrg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(miringCB))))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pekerjaanCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pekerjaanCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lakiRB)
                    .addComponent(prRB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mrg)
                            .addComponent(tebalCB)
                            .addComponent(ctk))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tampilBtn)
                            .addComponent(clearBtn)
                            .addComponent(tutupBtn))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(miringCB))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lakiRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRBActionPerformed

    private void tutupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupBtnActionPerformed
         dispose();
//        int balas = JOptionPane.showConfirmDialog(null,"Apakah yakin ingin keluar?", "Konfirmasi Keluar Aplikasi", 
//                JOptionPane.YES_NO_OPTION);
//        if (balas == JOptionPane.YES_OPTION) {
//        dispose();
//}
    }//GEN-LAST:event_tutupBtnActionPerformed

    private void tampilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilBtnActionPerformed
        String nama = namaTF.getText();
        String alamat = alamatTA.getText();
        String jk = "";
        String pekerjaan = String.valueOf(pekerjaanCB.getSelectedItem());

        // Pilih jenis kelamin
        if (lakiRB.isSelected()) {
            jk = lakiRB.getText();
        } else if (prRB.isSelected()) {
            jk = prRB.getText();
        }

        // Set cetak tebal dan miring
         int style = Font.PLAIN;

    if (tebalCB.isSelected() && miringCB.isSelected()) {
        style = Font.BOLD + Font.ITALIC;
    } else if (tebalCB.isSelected()) {
        style = Font.BOLD;
    } else if (miringCB.isSelected()) {
        style = Font.ITALIC;
    }

    // Set font ke hasilTA
    hasilTA.setFont(new Font("Arial", style, 12));

    // ⬇️⬇️ CETAK BIODATA KE TEXT AREA
    hasilTA.setText("Nama                : " + nama +
                    "\nAlamat              : " + alamat +
                    "\nPekerjaan        : " + pekerjaan +
                    "\nJenis Kelamin : " + jk);
    }//GEN-LAST:event_tampilBtnActionPerformed

    private void tebalCBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tebalCBStateChanged
         // Set cetak tebal
        Font tebal = new Font("Arial", Font.BOLD, 12);
        Font normal = new Font("Arial", Font.PLAIN, 12);
        
            if(tebalCB.isSelected()){
            hasilTA.setFont(tebal);
            }
            else{
                hasilTA.setFont(normal);
            }
    }//GEN-LAST:event_tebalCBStateChanged

    private void miringCBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_miringCBStateChanged
        // Set cetak miring
        Font miring = new Font("Arial", Font.ITALIC, 12);
        Font normal = new Font("Arial", Font.PLAIN, 12);
        
            if(miringCB.isSelected()){
            hasilTA.setFont(miring);
            }
            else{
                hasilTA.setFont(normal);
            }
    }//GEN-LAST:event_miringCBStateChanged

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        namaTF.setText("");
        alamatTA.setText("");
        jkBtnGroup.clearSelection();
        pekerjaanCB.setSelectedItem("Karyawan Swasta");
        hasilTA.setText("");

    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasi14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasi14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasi14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasi14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataOrganisasi14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTA;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel ctk;
    private javax.swing.JTextArea hasilTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.ButtonGroup jkBtnGroup;
    private javax.swing.JRadioButton lakiRB;
    private javax.swing.JCheckBox miringCB;
    private javax.swing.JLabel mrg;
    private javax.swing.JTextField namaTF;
    private javax.swing.JComboBox<String> pekerjaanCB;
    private javax.swing.JRadioButton prRB;
    private javax.swing.JButton tampilBtn;
    private javax.swing.JCheckBox tebalCB;
    private javax.swing.JButton tutupBtn;
    // End of variables declaration//GEN-END:variables
}
